---
version: "3.8"

services:
  frontend:
    image: frontendimage:latest
    ports:
      - "80:3000"        # âœ… ONLY public entry
    networks:
      - appnet

  auth:
    image: authimage:latest
    networks:
      - appnet

  book:
    image: bookimage:latest
    networks:
      - appnet

  borrow:
    image: borrowimage:latest
    networks:
      - appnet

  db:
    image: dbimage:latest
    networks:
      - appnet

networks:
  appnet:
    driver: overlay

