---
version: "3.8"

services:
  frontend:
    image: frontendimage
    ports:
      - "5000:5000"
    depends_on:
      - auth
      - book
      - borrow

  auth:
    image: authimage
    ports:
      - "5000:5000"

  book:
    image: bookimage
    ports:
      - "5001:5001"

  borrow:
    image: borrowimage
    ports:
      - "5002:5002"

  db:
    image: dbimage
    ports:
      - "3306:3306"

